name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: genarate crd
      run: just generate-crd
    - uses: nolar/setup-k3d-k3s@v1
      with:
        version: v1.26.5
    - name: install crd
      run: just install-crd
