name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build crdgen
      run: cargo build --bin crdgen --verbose
    
    - uses: nolar/setup-k3d-k3s@v1
      with:
        version: v1.26.5
    
    - run:  kubectl apply -f ckubectl apply -f charts/nats/templates/natscrd.yaml
